### ISSUE TITLE
Look at adding metrics to commons

### ISSUE THREAD

**Issue by phenixrizen** [netlify/netlify-commons#111]
We should look at adding metrics to commons considering multiple projects are starting to instrument metrics with statsd.

We could use github.com/netlify/eventeer/metriks as a starting point.

We could also look at using OpenCesus to collect both traces and metrics in commons.  This would give us a path to OpenTelemetry with bridging.  Or we could wait to implement this until OpenTelemetry is out of Beta.

**Comment by pandemicsyn** [comment]
I can send up a pr for this. The wrapper around go-metrics is handy but IMHO the most useful part of metriks is actually https://github.com/netlify/eventeer/blob/master/metriks/db_stats.go which pushes database driver metrics for you. Any reason we wouldn't wanna include that at this point?

**Comment by mheffner** [comment]
Imported in #117, would love feedback.

**Comment by mraerino** [comment]
I consider this fixed by the addition of `metriks`.

There also was a talk about it in the last infra arch chat: https://www.notion.so/netlify/2020-06-10-5b01cefbc67f47a2bef82ea98326b07f
