### ISSUE TITLE
create an easy integration with launch darkly

### ISSUE THREAD

**Issue by rybit** [netlify/netlify-commons#136]
We have more and more services that are going to be leveraging launch darkly, we should help by providing a "standard" way to integrate this into your go service. 

Mostly I'm thinking about:
- connection & configuration
- interfaces for flag checking (or use https://docs.launchdarkly.com/sdk/server-side/go directly)?
- noop versions for testing (unless they're provided?)

**Comment by mheffner** [comment]
I'm going to look at this for an upcoming project use. @vbrown608 added it to buildbot, so we could probably extract the common bits
