### ISSUE TITLE
kafka: Support all needed scenarios for Kafka consumers

### ISSUE THREAD

**Issue by smoya** [netlify/netlify-commons#164]
We want to support the following scenarios for Kafka consumers:

### Behavior:

- Consumer partitions are assigned automatically.
- Rebalance events are handled automatically by `librdkafka`.
- Consumer reads from latest stored offset. If none, earliest (could be changed). Configured [here](https://github.com/netlify/netlify-commons/blob/4b131f164bdfd1f17473f08edefcc602331f8fc5/kafka/consume.go#L60).

### Steps:

1. Create Consumer including `group.id`.
2. Call to `Subscribe` **without** a `Rebalance Callback` .
3. Start consuming.

### Behavior:

- Consumer partitions are assigned automatically.
- Rebalance events are handled locally in order to set the Initial offset after the first rebalance.
- Consumer reads from an specific offset.

### Steps:

1. Create Consumer including `group.id`.
2. Call to `Subscribe` and set a `Rebalance Callback` . In the first rebalance, this callback will assign the desired initial offset (calling `Assign`). Also de `Unassign` event should be handled gracefully.
3. Start consuming.

### Behavior:

- Consumer partitions are assigned **manually**.
- Several consumers can consume from the same partition.
- No rebalance events (not part of consumer group).

### Steps:

1. Create Consumer including a fake `group.id`. This is needed due to a limitation in `librdkafka`. See the following code in [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go/blob/d4b1fadc0776d02e9b74a1815f1e02dbb124fccd/kafka/consumer.go#L386-L392).
2. **Never** call to `Subscribe`
3. Call to `Assign` with the desired partition (use whatever hashing algorithm you want for deciding which partition to read from).
4. Start consuming.

**Comment by mraerino** [comment]
would be cool to split these scenarios into their own implementations so you can clearly select them by picking the correct reader impl.

**Comment by rybit** [comment]
I think that it is interesting to have the use cases written out (thanks!) but I don't see the need to refactor this at this point. Right now we get a consumer that has a pretty standard signature, and we have plenty of configuration options that are intuitive to me. 

I think we should get #161 merged in and if we end up finding this to be very cumbersome we can revisit it. To me it would be refactoring just to refactor.

**Comment by smoya** [comment]
The reason why I wrote those use cases is to set a guideline on what we need **now**. Have a clear path on what feature to work on and try to simplify the code we do as much as possible. 
The world of Kafka is deep, nothing that you learn by reading just one post, the same happens with libraries and implementations (like librdkafka). I'm not an expert at all, However I spent time testing and reading, especially the librdkafka implementation. That's why I wanted to add that value into the work we are doing right now, like in https://github.com/netlify/netlify-commons/pull/161.

Nothing about "refactoring just to refactor". I understand the suggestion @mraerino did (and I +1) about having implementations for each case is just a nice to have and can be done in a future iteration.

The important part here is not the Interface the library offers, but the internals it execute. In example, calling a `Subscribe()` on the consumer has some consequences (rebalance) that `Assign()`, which manually assigns partitions don't.
This, plus some other details are key to know, and this is the place to talk about them. Let's call it **The Basics of Kafka**.

**Comment by rybit** [comment]
Ok then I misunderstood the goal of this ticket. If it is a documentation thing, I love it. We might want to even push this into a README or comment on the constructor. 

I agree, we can figure out any changes in the interface after a few people have used it. 

@smoya how do you wanna proceed?
