### ISSUE TITLE
Support DataDog Distribution metric

### ISSUE THREAD

**Issue by mrdg** [netlify/netlify-commons#208]
https://godoc.org/github.com/DataDog/datadog-go/statsd#Client.Distribution
https://docs.datadoghq.com/metrics/distributions/

> Global distributions are designed to instrument logical objects, like services, independently from the underlying hosts. Unlike histograms which aggregate on the Agent-side, global distributions send all raw data collected during the flush interval and the aggregation occurs server-side

This seems to be the recommended way to record quantiles across different servers, as opposed to the [function](https://godoc.org/github.com/DataDog/datadog-go/statsd#Client.TimeInMilliseconds) we're using currently (which calculates percentiles on the agent and can't be aggregated afterwards). The Distribution api doesn't seem to be supported in armon/go-metrics, perhaps because it can't be supported in the other sinks. We could consider using the datadog package directly in netlify-commons/metriks.

**Comment by rybit** [comment]
I think moving off the armon version might be what we need to do. 😭 We also want to have an ability to report a value on a timer (e.g. keep a gauge fresh, or report only the last value on a period). 

I did do a quick and dirty integration with distribution metrics: https://github.com/netlify/pinger/blob/e4350a2843a277a9d1de24e6a1c3fb41e9ccbda1/report/report.go#L38-L60

Also, there is a very old version of a metrics package in commons: https://github.com/netlify/netlify-commons/tree/633daeda658f0244b152f5e2df7130c67d1a0811/metrics

**Comment by kitop** [comment]
Coming to add a +1 for this. It'd be really helpful to graph the subscription delay in analytics.
