### ISSUE TITLE
kafka: better respect context.Context in FetchMessage

### ISSUE THREAD

**Issue by cbosss** [netlify/netlify-commons#237]
https://github.com/netlify/netlify-commons/blob/c1a004d0f8e6998d8058e5cc68a0606ed5e67876/kafka/consume.go#L310-L337

This function might stall for 5 minutes before respecting a cancelled context. This might be too long for some usecases. We should either make the timeout configurable, or make `ReadMessage` context aware.

**Comment by rybit** [comment]
Kafka got moved out to a different repo.
