### ISSUE TITLE
Rename `msg` to `message` in JSON error serialization

### ISSUE THREAD

**Issue by kitop** [netlify/netlify-commons#286]
For context: https://github.com/netlify/netlify-react-ui/issues/9017

Main API returns errors as `{ code: 422, message: "message here" }` while the router serializes error messages as `{ code: 422, msg: "message here" }`, see https://github.com/netlify/netlify-commons/blob/6f5ed10a3a47c2782b539fe58432e009e9013acf/router/errors.go#L16

I'd like to change this to `message` for consistency and clarity. While the change is easy, it may impact other services so wanted to bring up the discussion of what could break and figure out a migration strategy if needed.

**Comment by mraerino** [comment]
Have you checked if the UI expects `msg` in any places, e.g. when contacting gotrue?
